#!/usr/bin/python3

import boto3
import ipaddress
import json
import os
import os.path

def read_config(interface: str):
    config_file_path = os.getenv("CONFIG_FILE", "/etc/route53_dyndns.json")
    if not os.path.exists(config_file_path):
        return None
    with open(config_file_path, "rb") as f:
        all_config = json.load(f)
    if interface not in all_config:
        return None
    return all_config[interface]

def get_client(config):
    client = boto3.client("route53", **config["client_options"])
    return client

def update_a_records(interface: str, address: ipaddress.IPv4Address)-> None:
    address_value = address.compressed
    config = read_config(interface)
    if not config:
        print(f"no configuration for {interface}")
        return
    client = get_client(config)
    for zone_id in config["zones"]:
        for hostname in config["zones"][zone_id]:
            changes = [
                {
                    'Action': 'UPSERT',
                    'ResourceRecordSet': {
                        'Name': hostname,
                        'Type': 'A',
                        'TTL': 300,
                        'ResourceRecords': [{'Value': address_value}],
                    },
                },
            ]
            response = client.change_resource_record_sets(
                HostedZoneId=zone_id,
                ChangeBatch={'Changes': changes})
            if response['ResponseMetadata']['HTTPStatusCode'] != 200:
                raise(RuntimeError('Update failed {}'.format(json.dumps(response))))

def update_aaaa_records(interface: str, address: ipaddress.IPv6Address) -> None:
    address_value = address.compressed
    config = read_config(interface)
    if not config:
        print(f"no configuration for {interface}")
        return
    client = get_client(config)
    for zone_id in config["zones"]:
        for hostname in config["zones"][zone_id]:
            changes = [
                {
                    'Action': 'UPSERT',
                    'ResourceRecordSet': {
                        'Name': hostname,
                        'Type': 'AAAA',
                        'TTL': 300,
                        'ResourceRecords': [{'Value': address_value}],
                    },
                },
            ]
            response = client.change_resource_record_sets(
                HostedZoneId=zone_id,
                ChangeBatch={'Changes': changes})
            if response['ResponseMetadata']['HTTPStatusCode'] != 200:
                raise(RuntimeError('Update failed {}'.format(json.dumps(response))))


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--interface", type=str)
    parser.add_argument("--ip-address", type=str)
    parser.add_argument("--ip6-address", type=str)
    args = parser.parse_args()
    interface = args.interface

    ip_address = None
    if args.ip_address:
        ip_address = ipaddress.IPv4Address(args.ip_address)
    if ip_address and ip_address.is_global:
        print(f"updating DNS A records")
        update_a_records(interface, ip_address)
    ip6_address = None
    if args.ip6_address:
        ip6_address = ipaddress.IPv6Address(args.ip6_address)
    if ip6_address and ip6_address.is_global:
        print("updating DNS AAAA records")
        update_aaaa_records(interface, ip6_address)
