ssh:
    authorized_keys:
        - ENC[AES256_GCM,data:8eHW8tezwqWLlK42r5MX7G+f8vc7UoBvPerULHh3n873uQRGHVxiBVrNrFYGxzRPds0O+mVOylXNL06uDFnHBEZkv1otXojBbiCaVn/O41JiwlemcRxFGk2GoSRTaslTLSLebtgaT5CMX2wDCbFr5gVSk41rCbdB+FsbdLWrymOmu2OJ5lIp6eON+RhPbeDPB/XGjkUkIqPTK6HsMeX6mWRaYxRFNypUcFHhKBm8H990rsp7W3Clp3LDYMaaEg/9Zh7AKw4hALvAnWyEuOjyz8fRNogTCI0BRVck6SzpUF534dkLBl8wNiUSkQSrA1wdXYMl8o49ocGgEktOIjT4fwoQ7HId911pgfg5nTVHkW+rUFzi9UUHg+wm5GgI97jSdjCJCdZdygIRBAd1bFlFXLf5kvo4QBXKu/tXgP8vEVNIbW2cPlzcypFTXvIb2G2fyHAfus03WJg4wP4rYvBOZNGO4ghzRXOT/6Jc5gY0BXw7vF7f0L20omWxT1gPt6DoLVpH/SCXTO6r44d+jf9tJPoPZrmtOZ+YdunKOb6KDcejB/S3Q2eHMHm3OF5QqiUiXg55VbQrbzl3RiHGQkKgVH6Jh3H9xhmhpxMmQrblZvEQVObjBUDI0T26qN47YteI4lGBMFxOPLBeRmwvQDNHMbXpjj+HmQsDSXYIs96QbcJQStIU4WuM0MFA21dm7jrUJJ/p5k8A2IJWgzrkZ7lQ3NEke02/8450VVyYg7fOJQ5Y1UcT0BVZfJYtk1pQvD2gXdiEM0Jy23vOmF4i6ioenVD1BVdgUPp7MoxEaCbLUoIh+eRy+M8MUc/7N/PbByAY5XZ6tHsZDgpbvke7A55X0/F6bUTqOp58t+f1cpwEXjxsVCpJ0aGPaaTLeU87gzhW94BUaWyLVaJGG7wXSbQ73+eOiefGO/hHeagmzloWGkCz/GF5Wt2ceQGuuzWluTV9S3OHxchzIDn5jLswSdAMTYykqsIoTicHTHDtaC6O0Lo=,iv:QFZLmm00CY+kJXWtS+9q+sGiIgkBwrnA8XwBqVvLGSw=,tag:+HZMjn9//agewiefgPwHOA==,type:str]
        - ENC[AES256_GCM,data:Sgs7m3sgu8NVJAp9AX10XIu6vCtLyXAQSobf33Qi2Aqm3kX8ErzqvRSrBq0Pmrm+y0F7yFqAeaKJXhVYJcrqSLxJfIfsANJrRXXCWRy7o8EQ2MXXONduTIU+BIWbYzpBGZgcV2bQ,iv:Ai6eL2hgitM37WiZCOv5YOETeRxvzC2CkAW6s0hXz0U=,tag:llndFJMHXew4B8OYQEGJIQ==,type:str]
address: ENC[AES256_GCM,data:84yVJU2sbJPMrKnWOSs=,iv:on5dY1vdF2WegZ+W/kC2AYe8WQchxF3KYM2djhfObHg=,tag:PeDs0yKhgN/1aR+VuOv1+A==,type:str]
wan_interface: ENC[AES256_GCM,data:qs8EjVK9,iv:xbvPwpHhhY0jpS4FrV+NqcjqQ9KEcm8EugrA1oJFtwY=,tag:yJ6LIqhPLwLZdgQOgyaI0w==,type:str]
lan_bridge: ENC[AES256_GCM,data:TVZP,iv:Jm6yUW1lXvK/+TZj1v3xkw7ujfZnS3R38Jt0JJWs1dA=,tag:/uh+M85vVHplZDMk+sUojQ==,type:str]
lan_interfaces:
    - ENC[AES256_GCM,data:LfAJJcrL,iv:0FVTIlmb36ZgarV/eZTQM7u6dWsjMsmH0J+rEKqLMeg=,tag:C1zDUK3l/sLlxP3EOmtr+A==,type:str]
    - ENC[AES256_GCM,data:CLS/Rg==,iv:IUaG3ghdakhQ0nz58TiyYJ0g/RqznSvbqRMUJA9dUuY=,tag:exu8Z1LkIgTqvj/aJ7qM0A==,type:str]
    - ENC[AES256_GCM,data:AhVCxpuT,iv:bBxNDsPcfozho3f1QF5bj+kXgwbcuD8QpplyUs8FV7U=,tag:ygrXFtVh1HvaZhv6s5eV0w==,type:str]
management_interface: ENC[AES256_GCM,data:btd7SC+b,iv:fPJb6bStf3079fxVMm1+teyyT1uioMVhvT4VqoRReIs=,tag:wU67JEe81b/qb644qy0Kfg==,type:str]
management_address: ENC[AES256_GCM,data:pXnVQzJEGJeCOR094nOc,iv:x08MqU4SEFt88eSw0tGdzuXBy9ggLCMxfSME/IwE5VU=,tag:A2J+qL05oYojOZi8CWBhlQ==,type:str]
management_network: ENC[AES256_GCM,data:yapX/tRgI0rdxCvdWune,iv:VlsdYEtvTxJsyR/EgUX3GRxCNRoZX7/kdP5DlZNIHz8=,tag:rsywcvCExjZtV6HYT0sr0w==,type:str]
ula:
    network: ENC[AES256_GCM,data:4lQNGhoU93jkSmpSfJxb9FyJtQ==,iv:WvOOUHGP3JlBRMaCWTykCwME4E3RiTfKJSWeWiJYpxA=,tag:X/xP/qBCw9oYerZjuyEdew==,type:str]
    address: ENC[AES256_GCM,data:B9opNuTa4auqvKjd1GOKjRk=,iv:BzBwOCSqAKJNvlXhsEuTZaXnn0noipvWO4Pgua1i9hQ=,tag:9kyfjUG9Q6SJnigTcEkasw==,type:str]
    netmask: ENC[AES256_GCM,data:wSw=,iv:+nDUt946d0UFjr51wg7DCRhtKZM8kfQFQx94kq+bJ1Y=,tag:3FwJ3wAuMmMigrTVmPdJ1w==,type:int]
hostname: ENC[AES256_GCM,data:isDF7huy,iv:pqTZjucQ3yfYWK7cjI0t+4I+890NRtHV8H8aT6t19pU=,tag:ExGItJjiOf4iYhZ0k6JbQA==,type:str]
domain: ENC[AES256_GCM,data:9xBxyZzTQI+M6gUiY4/gd1gJfhk=,iv:t9YNDh3IDXkOJOe47oR6H5qqO+Thvu8VcjB6v0cAPGg=,tag:1BkxZq2g0tproDSjKLwaMw==,type:str]
dhcp_range_start: ENC[AES256_GCM,data:1wkjk/tbIQQVINxs,iv:r/Usoxq7QdAZmtw1S87sar4gwtq94+b44ZudhtajrGM=,tag:pPWlGXCANI49My+QpBMMDg==,type:str]
dhcp_range_end: ENC[AES256_GCM,data:KYSx8Rt1PAbeQvA3Xw==,iv:j/QgLX/zJoURCfviB/kXOiZy3nb7IlLgOmSCJ9HsTJA=,tag:Xg0sgBaz3/5mDLDk9ZMb5w==,type:str]
dhcp_reservations:
    - address: ENC[AES256_GCM,data:uZ+pfaGKjyEoQ3M=,iv:UGQ90yVskiMid9NKcBZ+EWzvtz0OUvDieiYeLZI5fM4=,tag:LBCwth8aHrC+mb9foB3OnA==,type:str]
      name: ENC[AES256_GCM,data:xBIgrA==,iv:VF3LvxSeYSk9cmYQJpg3VxWtxlvreju/dyNPrk5rseE=,tag:AQI6rtvv0fqYeHC6720okQ==,type:str]
      mac: ENC[AES256_GCM,data:T7yflfamqIUXjaFx7f7DnC8=,iv:DS0lvTxtLkvc0LiAMK51iEbJcPwzUPhH85CKmeMu6xo=,tag:R9YyfqbsXa1a/I2zVleujQ==,type:str]
    - address: ENC[AES256_GCM,data:ga2HSG79l46zYkY=,iv:k8SLw3HmQxWm+waKudlQQCsx1/CYuSHbCKkDN6F24cE=,tag:m/VY7IL8hELLMBauhHyzVA==,type:str]
      name: ENC[AES256_GCM,data:JdIkY6hNLndbvoE=,iv:KQtvBe/X4sku9uDhNXKRzhEenySZ/TAjeLoi8o3sZgI=,tag:qm0eKjbO6D69FaImc9kmfw==,type:str]
      mac: ENC[AES256_GCM,data:AMsZazvBD5lBSEdn95i4jH0=,iv:9DYBnmAQkeIBwSG6x/51lTkhwuI79U58b/IjzXcczJg=,tag:H2apABUf77iOShnllVSJqA==,type:str]
    - address: ENC[AES256_GCM,data:tGQELXU0O9+rJqM=,iv:RASvzq3YAKA7NiGVtGk9rtvok7i55gif0z8T7Jl1r+s=,tag:28VsjPxdSrlFgmO5kUp99g==,type:str]
      name: ENC[AES256_GCM,data:Dck6MecwRXHP,iv:lzUDu47PxRsZDlh0x9SX2SUaqr1aJplkv7WUeeLjWJs=,tag:Juvdcbd2g8jmteGVtcRhRg==,type:str]
      mac: ENC[AES256_GCM,data:esz6wdhBzYk8IBeZVl0ACYc=,iv:nJSn7duoaD2ecAxW0HIKWmLf1UBV/Ge9JHRB2jc+5Nc=,tag:7BJJefV/yJmMLVyuMr3xKQ==,type:str]
    - address: ENC[AES256_GCM,data:OBhGFdZbaEEB36I=,iv:ipQ8JF2gyaaz8H2uedjJiVj3cRHDKf9y8dP+eP6artc=,tag:ccQpsVdlBM+nD2eYKDkwrA==,type:str]
      name: ENC[AES256_GCM,data:M6qadg==,iv:9+FrKNnR9jI/F3V6a4jb+6B/1zrbmGd4aQ5OitxnDyI=,tag:D7JWrqcNmGmPu/oVC/NlOg==,type:str]
      mac: ENC[AES256_GCM,data:2dQR+0OwvIEGuq4V2ef0UD4=,iv:mJfX/5RgYYh0TytmXdvitNFMSEp4Dt7tecQuvlNVyEk=,tag:QycVNXRPype6QXK24JGlCg==,type:str]
    - address: ENC[AES256_GCM,data:6fosCFX4ITIxzYA=,iv:TOmHis/2p+jsbA9xSjAuYYRpea6Yk1aA6J2Ate0wkmo=,tag:fili1RDM1Bg4GzVUJN2sAA==,type:str]
      name: ENC[AES256_GCM,data:RMC+ENkk,iv:iDBxLq0hzLch5QtCSQeQqr5pOASdyUhRQPWVTHvxeN8=,tag:q/Q96RRLOVwhNUYAk9jzww==,type:str]
      mac: ENC[AES256_GCM,data:rRleVe1zI7BmtEyTRNYkJQU=,iv:Ylj2bN2eo/0U23jcgnDZjov1+d5Qf+9/3Ich1VSfcLc=,tag:+fByjyyXSp1C4UIXvmZ0bA==,type:str]
    - address: ENC[AES256_GCM,data:HrdCmcFbdYPRib8=,iv:MID/z1vUHjZlAJmgjE+1ONclcd1x9DaY8ezVCJRGqrE=,tag:YqD82P+8FDmZD4VV8d0QGg==,type:str]
      name: ENC[AES256_GCM,data:R7bAAorcSLsLEFI=,iv:roI+qivkaXak2+/KC2Waa6HMhcxbCIir2tB6Fva/koo=,tag:lkCG4zsJenw+OdzxPh3ZEw==,type:str]
      mac: ENC[AES256_GCM,data:wNpANlJVPkvLSsVMfAvlvDI=,iv:CLnW0SQux/kqb1ui0FOUQame9H9iRHiZXZ9umrMwfIc=,tag:cVgRM8szSs6PhMLthtW4kw==,type:str]
    - address: ENC[AES256_GCM,data:hrD9J43uMY6mml2A,iv:GOR2ZgOfd6YCMwYuO1iri5bZmO5D0sufSNE16pQs9UE=,tag:N+lOl0tjiV7MEeMhS/2fkA==,type:str]
      name: ENC[AES256_GCM,data:lC8ONESSn9WDw7c=,iv:db8iQyTA1lCjkKPvFTxObrPHIOzL9HmQg89NwJcPV2Q=,tag:sC1pmLs9uCaEGgVhu+LMOw==,type:str]
      mac: ENC[AES256_GCM,data:SuvnH+SgfR0N1GGhUEt3KmA=,iv:FCHQrF92JWyqOd1hvblkJxzJj9nX27T7GS8sxK9Z3Ow=,tag:CIdFhxdCdjCjB0hcR+tdrA==,type:str]
    - address: ENC[AES256_GCM,data:RYMDLss9GyEa0NRK,iv:FFk7QLxL0qVaHHURoWYwcBdPyLYPSzdloUAEPzJgrXw=,tag:dyHMfyCSfNWO2n34eYIEQg==,type:str]
      name: ENC[AES256_GCM,data:TO0WLHrPNg==,iv:YW3qEUkTs38IvoNgMbc/8jva00UMuT26tkXOIWaKJUc=,tag:LKJ3s+OSHlsdwECyKJsWoQ==,type:str]
      mac: ENC[AES256_GCM,data:uqhQgr2g3A6XMheMMeD4mYM=,iv:TRrY88zGf/mX00setdV+FkP7hnRVPQp3dkdjEtSWUr8=,tag:5J4VDg0WPxfI69rQPKRkSg==,type:str]
dns_servers:
    ipv4:
        - ENC[AES256_GCM,data:k1Mt+T7rUg==,iv:sbWCB1yztIdk9JrbbKYnauzFKKcjreEP/3gl/YTqYxo=,tag:giS1H0f/r4v2/q1pFT5ijg==,type:str]
        - ENC[AES256_GCM,data:3zVOdaOoGw==,iv:/1ZOVyCrP5dEQvNi3ZDci9r3VXztNSyR/CVLJfB8Cxc=,tag:y5nfu5R/IgoYyXasOFttVA==,type:str]
    ipv6:
        - ENC[AES256_GCM,data:8Do5Df38VYkwVzlK0fYu/iS6G0Y=,iv:92WeqqLBlvVo3kjkN9CkBS+hED2L9JNBw56O53a9Oy8=,tag:102IAxRgqD1CjTqeBH2eQg==,type:str]
        - ENC[AES256_GCM,data:rdBie7PxPCgw3luIB5ng8aru9nE=,iv:3BhqGj90vybKc/7pIw1qDcna/uZoZUMe25CQv/8OuQw=,tag:wa4JNwUgA+2ECwZfDC47Lg==,type:str]
sops:
    lastmodified: "2025-09-05T01:30:32Z"
    mac: ENC[AES256_GCM,data:pxcym97NuMhNsuh44+EOm0eP1iXqcqwZinztQm3qqmrwJV6dFEeLZ2Chvg3pxuCySZ5rGazq89UuXJ1P1s8BO6Rn+7Ez0C5l9MNOQJxET0GMtsdJB3oZlIVHcsuww5PFG5p+8uQ8uSmZziyHqIGVMVzJH4I2PpLAROgLK8pEn+s=,iv:6g/VvDh6FT9pdazqi+l0u8cklbTl3v4+0tjDqYJs3wA=,tag:/o3YwHu15W8iU6bn0Ytibw==,type:str]
    pgp:
        - created_at: "2025-09-04T23:23:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8EJgGJn6JzqAQ/9E1JBNs18L5TwggvwM8JkuBDcP3ElpXrUO8ej/PPU2V8P
            ksFLP4j1/B0ipT0DIZ9ofmPlfccQO7FBbhcuJEDfb49dpHAvLgh1CKrngH782Nns
            w+JUhZiHjodzN8uBC46Y6ZkYcnb9mBzy4cl9TApnbDpJwo+/ackQlOZRPg6owk5n
            Q4XH55sC6EubjncAomcNEyUiTJ+5Ic/50lIdhwmKS7aq7M4/qAHGPFWP2VprbRK5
            5+O0G+L/JHOCP3sICi/f3m/ajr8yWnhr/388zmSNkqnKg+83fnDvbEAfhvx0PBD4
            BvcNxuuXGmpJiN/g1jsYK5O5YytchgyBvKvb6yUcVA/Efd2Djfkqi/u+k6GKxfzF
            WeR2lcJRKos/9eh/k2/MQLtED8JFRvFZN9yRfVz7Cqoa/3jFHoHZMiOy3+2++CIy
            lKaDkTge4wAbd4Ixfutsn8ajuqdEBVRRlx6zNbFBHiyaI9GFandK3QZ3RBYP3vlt
            LomQD30q/lm40iKZnWg3itrssWlEMnYl1Np/Z/O2Py0y+xjsU+p+dfQ//xYmYrqx
            PYu3CHksp+/mtYLYfDRZxIDPHOL2IFcPPQ1n7cVgWDJcvfqajSrG3TocNgFfc4H2
            sTBxvKrYlCpJ/we/tnddbIsEl392rrX9j6jlDqRkBUbSlHbKpk+8NaWyVFoiNx3S
            XAG97d2/4G2gLyfmNBff1LpsOsTMQMKjemb0dI8QZlUvM3xecXVuMJzUqcpgmL3v
            OdKsi8q7j1bovanTaHzQimkNcwBQQfRKlI26tOoY9OAay9uhsOLHeLA+HxPs
            =5jVB
            -----END PGP MESSAGE-----
          fp: B95838FE4ED98AF87900073BE264A63D28D07D08
    unencrypted_suffix: _unencrypted
    version: 3.10.2
